/* -- Database Exploration -- */
-- Explore all objects in the Database
Select * From INFORMATION_SCHEMA.TABLES

-- Explore all columns in the Database
Select * From INFORMATION_SCHEMA.COLUMNS
Where TABLE_NAME = 'dim_customers'


/* -- Dimension Exploration -- */
-- Explore all Countries our customers come from.
SELECT DISTINCT country From gold.dim_customers

-- Explore all categories "The major Divisions"
SELECT DISTINCT category, subcategory, product_name From gold.dim_products
Order by 1,2,3

/* -- Date Dimension Exploration -- */
-- Find the Date of the first and last order
SELECT
	MIN(order_date) as first_order,
	MAX(order_date) as last_order,
	DATEDIFF(year, MIN(order_date),MAX(order_date)) As order_range_year,
	DATEDIFF(month, MIN(order_date),MAX(order_date)) As order_range_month
From gold.fact_sales

-- Find the youngest and oldest customer
SELECT
	MIN(birthdate) as oldest_birthdate,
	DATEDIFF(year, MIN(birthdate), GETDATE()) as oldest_age,
	MAX(birthdate) as oldest_birthdate,
	DATEDIFF(year, MAX(birthdate), GETDATE()) as oldest_age
From gold.dim_customers

/* -- Measure Exploration -- */
SELECT * FROM gold.fact_sales

-- Find the total sales
SELECT SUM(sales_amount) as total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT Sum(quantity) as total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) as average_price From gold.fact_sales

-- Find the total number of orders
-- SELECT Count(order_number) as total_sales FROM gold.fact_sales
SELECT Count(DISTINCT order_number) as total_sales FROM gold.fact_sales

-- Find the total number of products
SELECT Count(product_name) as total_products from gold.dim_products
SELECT Count(DISTINCT product_key) as total_products from gold.dim_products

-- Find the total number of customers
SELECT Count(customer_key) as total_customers from gold.dim_customers

-- Find the total number of customers that has placed an orders
SELECT Count(DISTINCT customer_key) as total_customers FROM gold.fact_sales

-- Generate a report that shows all key metrics of the business
SELECT 'Total Sales' as measure_name, SUM(sales_amount) as measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', Sum(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) From gold.fact_sales
UNION ALL
SELECT 'Total Orders Number', Count(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products Number', Count(product_name) from gold.dim_products
UNION ALL
SELECT 'Total Customers', Count(DISTINCT customer_key) FROM gold.fact_sales

/* -- Magnitude Analysis: compare the measure value by categories -- */
SELECT * FROM gold.dim_customers

-- Find total customers by countries
Select 
	country, 
	COUNT(customer_id) as total_customer 
From gold.dim_customers
Group by country
Order by total_customer desc

-- Find total customers by gender
SELECT 
	gender,
	COUNT(customer_key) as total_customers
FROM gold.dim_customers
Group by gender
Order by total_customers desc

-- Find total products by category
SELECT
	category,
	COUNT(product_key) as total_products
FROM gold.dim_products
Group by category
Order by total_products desc

-- What is the average costs in each category?
SELECT
	category,
	AVG(product_cost) as average_cost
FROM gold.dim_products
Group by category
Order by average_cost desc

-- What is the total revenue generated for each category?
SELECT
	p.category,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products p
ON fs.product_key = p.product_key
Group by p.category
Order by total_revenue desc

-- Find total revenue is generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) as total_revenue
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
Group by
	c.customer_key,
	c.first_name,
	c.last_name
Order by total_revenue desc

-- What is the distribution of sold items across countries?
SELECT
	c.country,
	COUNT(product_key) as total_item
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
Group by c.country
Order by total_item desc
